# Generated by Django 3.0.6 on 2020-06-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorproduct',
            old_name='default_image',
            new_name='is_default_image',
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(max_length=45, null=True),
        ),
    ]
