# Generated by Django 3.0.6 on 2020-07-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20200616_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
